name: CI with SonarQube and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main1

jobs:
  ci-pipeline:
    runs-on: [self-hosted, macos]
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run SonarQube analysis
      - name: Run SonarQube scanner
        env:
          SONAR_HOST_URL: http://localhost:9000 # SonarQube on localhost
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Secret stored in GitHub
        run: |
          npx sonarqube-scanner

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsa-nodejs:latest .

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rsa-nodejs:latest

      # Step 8: Run Docker container from Docker Hub image (Locally)
      - name: Run Docker container from Docker Hub image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/rsa-nodejs:latest
          docker run -d --name rsa-js -p 80:80 ${{ secrets.DOCKER_USERNAME }}/rsa-nodejs:latest
